# Generated by Django 5.2.13 on 2026-04-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='principal_currency',
            field=models.CharField(choices=[('BIF', 'BIF'), ('USD', 'USD'), ('EUR', 'EUR')], default='BIF', max_length=50),
        ),
    ]
