# Generated by Django 5.2.13 on 2026-04-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_user_principal_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='principal_currency',
            field=models.CharField(choices=[('BIF', 'Franc Burundais'), ('USD', 'Dollar US'), ('EUR', 'Euro')], default='BIF', max_length=50),
        ),
    ]
