# Generated by Django 5.2.13 on 2026-05-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_useremail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useremail',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
