# Generated by Django 5.2.13 on 2026-04-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MOBILE', 'Mobile'), ('BANK', 'Bank')], default='CASH', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(blank=True, choices=[('BIF', 'Franc Burundais'), ('USD', 'Dollar US'), ('EUR', 'Euro')], max_length=50, null=True),
        ),
    ]
