# Generated by Django 5.2.13 on 2026-04-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_categorytype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('expense', 'Dépense'), ('income', 'Revenu')], max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='CategoryType',
        ),
    ]
