# Generated by Django 5.2.13 on 2026-05-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='total_amount_saved',
            new_name='amount_saved',
        ),
        migrations.AlterField(
            model_name='target',
            name='start_target_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
