# Generated by Django 5.2.13 on 2026-05-13 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_rename_total_amount_saved_target_amount_saved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='amount_saved',
            new_name='initial_amount',
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_date', models.DateTimeField(auto_now_add=True)),
                ('amount_to_contributed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions_created_by', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='management.target')),
            ],
        ),
    ]
