# Generated by Django 5.2.13 on 2026-05-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_account_options_account_account_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ['id']},
        ),
    ]
